pull_request_rules:
  - name: Automatic merge backend if checks pass (backend, cmd)
    conditions:
      - files~=^(!?cmd/backend)
      - check-success=verify-service-backend
      - label=ready-to-merge
      - "#check-failure=0"
    actions:
      merge:
        method: squash
        strict: true
        strict_method: rebase

  - name: Automatic merge backend if checks pass (shared package, server)
    conditions:
      - files~=^(!?pkg/server)
      - check-success=verify-pkg-server
      - label=ready-to-merge
      - "#check-failure=0"
    actions:
      merge:
        method: squash
        strict: true
        strict_method: rebase

  - name: Automatic merge backend if checks pass (shared package, secret)
    conditions:
      - files~=^(!?pkg/secret)
      - check-success=verify-pkg-secret
      - label=ready-to-merge
      - "#check-failure=0"
    actions:
      merge:
        method: squash
        strict: true
        strict_method: rebase

  - name: Automatic merge backend if checks pass (internal, backend)
    conditions:
      - files~=^(!?internal/backend)
      - check-success=verify-service-backend
      - label=ready-to-merge
      - "#check-failure=0"
    actions:
      merge:
        method: squash
        strict: true
        strict_method: rebase

