pull_request_rules:
  - name: Automatic merge backend if checks pass
    conditions:
      - files~=^(!?applications/backend)
      - check-success=verify
      - label=ready-to-merge
    actions:
      merge:
        method: squash
        strict: true
        strict_method: rebase

