pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - files~=^(!?applications/backend)
      - check-success=verify
      - label=ready-to-merge
    actions:
      merge:
        method: merge

