#!/bin/sh
# generated by bcrypt
password='$2a$10$7XCgQX2LmoD0JbhI6f4zi.wjzTSGckMzkzkYm42DFk/6NJc1.ve6K'

kubectl -n argocd patch secret argocd-secret \
  -p '{"stringData": {
    "admin.password": "'${password}'",
    "admin.passwordMtime": "'$(date +%FT%T%Z)'"
  }}'
