on:
  push:
    branches:
      - main
    paths:
      - 'pkg/server/**'
      - 'pkg/secret/**'
      - 'pkg/container/**'
      - 'internal/backend/**'
      - 'docker/backend/Dockerfile'
      - '.github/workflows/backend_main.yaml'
      - 'cmd/backend/**'

jobs:
  build-service-backend:
    name: build-service-backend
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.4'
      - run: go build -a -installsuffix cgo -o bin/backend ./cmd/backend
        env:
          CGO_ENABLED: "0" 
          GOOS: linux
          GOARCH: amd64
      - run: ls -lah bin/backend
      - run: echo $CR_PAT | docker login ghcr.io -u vranystepan --password-stdin
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
      - run: docker build -t ghcr.io/pipetail/argocd-blueprint/backend:${{ github.sha }} -f docker/backend/Dockerfile .
      - run: docker push ghcr.io/pipetail/argocd-blueprint/backend:${{ github.sha }}

  deployment-manifests-backend:
    name: deployment-manifests-backend
    runs-on: ubuntu-20.04
    needs:
      - build-service-backend
    steps:
      - uses: actions/checkout@v2
      - run: sed -i "s|local defaultTag = .*;|local defaultTag = \"${{ github.sha }}\";|g" deploy/backend/deployment.jsonnet
      - run: grep "defaultTag" deploy/backend/deployment.jsonnet
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.CR_PAT }}
          commit-message: '[Deployment][Backend] update current image tag'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: deploy/${{github.sha}}
          delete-branch: true
          title: '[Deployment][Backend] update current image tag'
          assignees: ${{ github.actor }}
          draft: false
          labels: |
            ready-to-merge
            deployment
            automated

# docker login uses personal access token because that's the only supported variant right now:
#   https://docs.github.com/en/free-pro-team@latest/packages/managing-container-images-with-github-container-registry/pushing-and-pulling-docker-images#authenticating-to-github-container-registry
#   https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets

# github action is not triggered if it's pushed with GITHUB_TOKEN:
#   actions need PAT https://github.com/peter-evans/create-pull-request/issues/48