on:
  push:
    branches:
      - main
    paths:
      - 'applications/backend/**'
      - 'pkg/server/**'
      - 'internal/backend/**'
      - 'docker/backend/Dockerfile'
      - '.github/workflows/backend_main.yaml'

jobs:
  build-service-backend:
    name: build-service-backend
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.4'
      - run: go build -o bin/backend ./cmd/backend
      - run: ls -lah bin/backend
      - run: echo $CR_PAT | docker login ghcr.io -u vranystepan --password-stdin
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
      - run: docker build -t ghcr.io/pipetail/argocd-blueprint/backend:${{ github.sha }} -f docker/backend/Dockerfile .
      - run: docker push ghcr.io/pipetail/argocd-blueprint/backend:${{ github.sha }}

  deployment-manifests-backend:
    name: deployment-manifests-backend
    runs-on: ubuntu-20.04
    needs:
      - build-service-backend
    steps:
      - uses: actions/checkout@v2
      - run: sed -i "s|local defaultTag = .*;|local defaultTag = \"${{ github.sha }}\";|g" deploy/backend/main.jsonnet
      - run: grep "defaultTag" deploy/backend/main.jsonnet
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: '[Deployment][Backend] update current image tag'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: deploy/${{github.sha}}
          delete-branch: true
          title: '[Deployment][Backend] update current image tag'
          assignees: ${{ github.actor }}
          draft: false
