on:
  pull_request:
    paths:
      - 'applications/backend/**'
      - 'pkg/server/**'
      - 'internal/backend/**'
  
jobs:
  verify-service-backend:
    name: verify-service-backend
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.4'
      - run: go build -o bin/backend ./cmd/backend